name: 'Code Quality'
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  analysis-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: run static analysis
        run: npm run static:analysis

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: run unit test
        run: npm run test:unit

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: build project
        run: npm run build

      - name: package project
        run: npm run package

      - uses: ./
        with:
          repository: 'hyperjumptech/procheck-configs'
          configPath: 'procheck-integration-test/procheck.json'

      - uses: ./
        with:
          repository: 'hyperjumptech/procheck-private-configs'
          configPath: 'procheck-integration-test/procheck.json'
          githubToken: ${{ secrets.PROCHECK_GITHUB_TOKEN }}
